---
title: "About Me"
description: |
  An Overview of My Project
---

## About Me

My Name is Noel Jung and I am a Bachelor of Health Sciences Student at Queens University. I enjoy swimming and reading. This is my first experience coding in R and in data science.

Email: noeljjung@gmail.com

## About the Project

My final project investigates if changes in an increase in temperature is correlated with an increase in the number of West Nile and Lyme Disease cases. More about this topic can be seen on the home page. I chose this project because I wanted to pursue this topic for an old project, however I lacked the skill to conduct it properly. I wanted to try again with this website and with my newfound skills in coding and data science.

## Link to my Github Repository for my Wesbite

<https://github.com/NoelJung/Temperature-and-Vector-Diseases>

## Credits

I learned how to code in R through Dr. David Kane's data science course. The website to the course can be found here:

<https://bootcamp.davidkane.info/>